### ISSUE TITLE
Architectural Decision Records

### ISSUE THREAD

**Issue by hombinator** [TopInvestor4000/ResourceMaster#34]
https://github.com/adr/madr
https://github.com/adr/madr/blob/main/template/adr-template.md
-> metadaten sind wichtig (werden nächstes mal angeschaut)

**Comment by busykoala** [comment]
@hombinator 

**k8s:**
- complete stack can be deployed and managed in a declarative manner
- high resilience and can easily be optimized for very high up-time
**zhaw-lab:**
- price (free)
- more flexibility regarding other services than resourcemaster (postgres DB, logging setup)
**Loki:**
- basically no indexing and therefore low resource usage unless in use
**Grafana:**
- fits best with Loki and currently only used for log aggregation
**Postgres DB:**
- open source
- very close to SQL standards
- team knows it best (DB module from university was PG specific)
**Blazor/.NET:**
- devs in our team have good C# knowledge
- easy handling due to server/client development in the same stack
- great debugging due to Blazor magic for server/client breakpoints

**Comment by busykoala** [comment]
Wurde hier erfasst: https://github.com/TopInvestor4000/ResourceMaster/wiki/13.-Decision-Log

**Comment by flo-graf** [comment]
Added sub pages for each major decision. Ongoing task, leaving it open in case any big decisions are taken.
